const CHANGE_THEME = "CHANGE_THEME";
const SET_INPUT_VALUE = "SET_INPUT_VALUE";
const SET_FILTER_TYPE="SET_FILTER_TYPE"
const SET_ORDER_TYPE="SET_ORDER_TYPE"
const SET_PAGE="SET_PAGE"

export{
    CHANGE_THEME,
    SET_INPUT_VALUE,
    SET_FILTER_TYPE,
    SET_ORDER_TYPE,
    SET_PAGE
}